on: push

jobs:
  commands:
    runs-on: ubuntu-latest
    steps:
      - run: echo "::group::Messages are grouped"
      - run: echo "::debug::Set the Octocat variable"
      - run: echo "::notice title=Notice title::Some notice message"
      - run: echo "::warning title=Warning title::Some warning message"
      - run: echo "::error title=Error title::Some error message"
      - run: echo "::endgroup::"
      - run: echo "### All tests passed! :rocket:" >> $GITHUB_STEP_SUMMARY
      - run: 'echo "- Mobile: 12\12 " >> $GITHUB_STEP_SUMMARY'
      - run: 'echo "- Desktop: 7\7 " >> $GITHUB_STEP_SUMMARY'
      - run: 'echo "- Integration: 23\23 " >> $GITHUB_STEP_SUMMARY'
