on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo test

  static-checks:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo test

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo test

  notify:
    needs:
      - test
      - static-checks
    runs-on: ubuntu-latest
    steps:
      - run: echo test
